CREATE DATABASE University

GO
USE University
GO

CREATE TABLE Majors(
    MajorID INT PRIMARY KEY IDENTITY,
    [Name] NVARCHAR(50) NOT NULL
)

CREATE TABLE Subjects(
    SubjectID INT PRIMARY KEY IDENTITY,
    SubjectName NVARCHAR(50) NOT NULL
)

CREATE TABLE Students(
    StudentID INT PRIMARY KEY IDENTITY,
    StudentNumber NVARCHAR(50) NOT NULL,
    StudentName NVARCHAR(50) NOT NULL,
    MajorID INT REFERENCES Majors(MajorID) NOT NULL
)

CREATE TABLE Payments(
    PaymentID INT PRIMARY KEY IDENTITY,
    PaymentDate DATETIME2 NOT NULL,
    PaymentAmount DECIMAL(10, 2) NOT NULL,
    StudentID INT REFERENCES Students(StudentID) NOT NULL
)

CREATE TABLE Agenda(
    StudentID INT REFERENCES Students(StudentID) NOT NULL,
    SubjectID INT REFERENCES Subjects(SubjectID) NOT NULL,
    PRIMARY KEY (StudentID, SubjectID)
)